# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: 'default'
  vmImage: 'windowagents'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'


- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(3)(eb253cc2-38a8-4f6f-bdf7-d14de91f1ebd)'
    appType: 'webApp'
    appName: 'SwasthamWebApp'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'


- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

